import vazirFont from "@/constants/localFont";
import "@/styles/globals.css";
import { Toaster } from "react-hot-toast";
import AuthProvier from "@/context/AuthContext";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { Suspense } from "react";
import Loading from "@/components/ui/Loading";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" className="">
      <body className={`min-h-screen  ${vazirFont.variable} font-sans `}>
        <Toaster />
        <Suspense fallback={<Loading />}>
          <ReactQueryProvider>
            <AuthProvier>{children}</AuthProvier>
          </ReactQueryProvider>
        </Suspense>
      </body>
    </html>
  );
}
